name: Release tlgspider binaries

on:
  push:
    tags:
      - 'v*'  # 仅在推送如 v1.0.0 这类 tag 时触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tlgspider-linux
            ext: ""
          - os: windows-latest
            artifact_name: tlgspider-windows
            ext: ".exe"
          - os: macos-latest
            artifact_name: tlgspider-macos
            ext: ""

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build with PyInstaller using .spec
      run: |
        pyinstaller tlgspider.spec

    - name: Rename output binary
      run: |
        mv dist/tlgspider dist/${{ matrix.artifact_name }}${{ matrix.ext }}
      shell: bash

    - name: Upload artifact for Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.artifact_name }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
